"""
Mock engine data — generated by generate_from_positions.py from positions.py + ShashChess.
Do not edit manually. Re-run generate_from_positions.py to refresh.
"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class EngineResult:
    fen: str
    best_move_uci: str
    best_move_san: str
    score_cp: Optional[int]
    mate_in: Optional[int]
    wdl_win: int
    wdl_draw: int
    wdl_loss: int
    depth: int
    shashin_type: str
    side_to_move: str
    played_move: str   # move actually played (for LLM context)


def get_shashin_type(score_cp):
    if score_cp is None: return "Tal"
    if abs(score_cp) < 50: return "Capablanca"
    if abs(score_cp) > 150: return "Tal" if score_cp > 0 else "Petrosian"
    return "Capablanca"


MOCK_POSITIONS: dict[str, EngineResult] = {
    # pos_00 — 27... Ne7
    "pos_00": EngineResult(
        fen="8/1bp4p/p3P1p1/3n4/3kN1P1/5P1P/P1P2K2/8 b - - 0 0",
        best_move_uci="b7c8",
        best_move_san="Bc8",
        score_cp=386, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="black",
        played_move="Ne7",
    ),

    # pos_01 — 17... h5
    "pos_01": EngineResult(
        fen="r1b1k2r/ppppb1qp/2n2n2/6p1/2PP1p2/P1NB1N1P/1P2R1P1/R1BQ2K1 b - - 0 0",
        best_move_uci="d7d6",
        best_move_san="d6",
        score_cp=-62, mate_in=None,
        wdl_win=0, wdl_draw=840, wdl_loss=160,
        depth=15, shashin_type="Capablanca",
        side_to_move="black",
        played_move="h5",
    ),

    # pos_02 — 23. Nh6
    "pos_02": EngineResult(
        fen="r1b1k1q1/ppppb2r/2P2n2/5N1p/2P3p1/P1NB3P/1P2Q1P1/R1B3K1 w - - 0 0",
        best_move_uci="h3h4",
        best_move_san="h4",
        score_cp=287, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Nh6",
    ),

    # pos_03 — 22. Nd8+
    "pos_03": EngineResult(
        fen="1r3rk1/3bqNbp/pp1p2p1/2pB4/P2PP1n1/2P1B3/1P1Q2PP/R4RK1 w - - 0 0",
        best_move_uci="f7d8",
        best_move_san="Nd8",
        score_cp=467, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Nd8+",
    ),

    # pos_04 — 27. Qxh6+
    "pos_04": EngineResult(
        fen="1r2qb2/3b1Nkp/pp1p2pn/2pB4/P2PP3/2P5/1P1Q2PP/R5K1 w - - 0 0",
        best_move_uci="d2h6",
        best_move_san="Qxh6",
        score_cp=None, mate_in=11,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Qxh6+",
    ),

    # pos_05 — 5. Ngf3
    "pos_05": EngineResult(
        fen="r1bqkbnr/ppp2ppp/8/3pn3/8/4P3/PPPN1PPP/R1BQKBNR w - - 0 0",
        best_move_uci="g1f3",
        best_move_san="Nf3",
        score_cp=-9, mate_in=None,
        wdl_win=10, wdl_draw=960, wdl_loss=20,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="Ngf3",
    ),

    # pos_06 — 9... Qd6
    "pos_06": EngineResult(
        fen="r1bqk2r/ppp2ppp/8/3nb3/8/4PN2/PP3PPP/R1BQKB1R b - - 0 0",
        best_move_uci="e5f6",
        best_move_san="Bf6",
        score_cp=1, mate_in=None,
        wdl_win=10, wdl_draw=990, wdl_loss=10,
        depth=15, shashin_type="Capablanca",
        side_to_move="black",
        played_move="Qd6",
    ),

    # pos_07 — 11. e5
    "pos_07": EngineResult(
        fen="rn1q1rk1/1b2bppp/p2ppn2/1p6/3NPP2/1BN1B3/PPP3PP/R2Q1RK1 w - - 0 0",
        best_move_uci="e4e5",
        best_move_san="e5",
        score_cp=19, mate_in=None,
        wdl_win=40, wdl_draw=960, wdl_loss=10,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="e5",
    ),

    # pos_08 — 16. Qe2
    "pos_08": EngineResult(
        fen="r2r2k1/1b1nbppp/pqn1p3/1p2P3/5B2/1BN2N2/PPP3PP/R2Q1R1K w - - 0 0",
        best_move_uci="d1e2",
        best_move_san="Qe2",
        score_cp=-105, mate_in=None,
        wdl_win=0, wdl_draw=490, wdl_loss=510,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="Qe2",
    ),

    # pos_09 — 17... Qc7
    "pos_09": EngineResult(
        fen="r2r2k1/1b2bppp/pqn1p3/1pn1P3/8/1BN1BN2/PPP1Q1PP/R4R1K b - - 0 0",
        best_move_uci="c6a5",
        best_move_san="Na5",
        score_cp=74, mate_in=None,
        wdl_win=230, wdl_draw=770, wdl_loss=0,
        depth=15, shashin_type="Capablanca",
        side_to_move="black",
        played_move="Qc7",
    ),

    # pos_10 — 20... Nb4
    "pos_10": EngineResult(
        fen="r4rk1/1bq1bppp/p1n1p3/1p2P3/8/1PN1BN2/1PP2QPP/3R1R1K b - - 0 0",
        best_move_uci="c6b4",
        best_move_san="Nb4",
        score_cp=71, mate_in=None,
        wdl_win=170, wdl_draw=830, wdl_loss=0,
        depth=15, shashin_type="Capablanca",
        side_to_move="black",
        played_move="Nb4",
    ),

    # pos_11 — 1... e5
    "pos_11": EngineResult(
        fen="rnbqkbnr/pppppppp/8/8/P7/8/1PPPPPPP/RNBQKBNR b - - 0 0",
        best_move_uci="e7e5",
        best_move_san="e5",
        score_cp=38, mate_in=None,
        wdl_win=80, wdl_draw=910, wdl_loss=10,
        depth=15, shashin_type="Capablanca",
        side_to_move="black",
        played_move="e5",
    ),

    # pos_12 — 3. e4
    "pos_12": EngineResult(
        fen="r1bqkbnr/pppp1ppp/2n5/4p3/P1P5/8/1P1PPPPP/RNBQKBNR w - - 0 0",
        best_move_uci="e2e3",
        best_move_san="e3",
        score_cp=-93, mate_in=None,
        wdl_win=0, wdl_draw=600, wdl_loss=400,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="e4",
    ),

    # pos_13 — 6... d6
    "pos_13": EngineResult(
        fen="r1bqk2r/pppp1ppp/2n2n2/4p3/P1P1P3/3P4/1P1N1PPP/R2QKBNR b - - 0 0",
        best_move_uci="a7a5",
        best_move_san="a5",
        score_cp=108, mate_in=None,
        wdl_win=540, wdl_draw=460, wdl_loss=0,
        depth=15, shashin_type="Capablanca",
        side_to_move="black",
        played_move="d6",
    ),

    # pos_14 — 9... Nxh6
    "pos_14": EngineResult(
        fen="r1bq1rk1/ppp2ppp/2np3P/4p3/P1P1P1n1/3P4/1P1N1PP1/R2QKBNR b - - 0 0",
        best_move_uci="g4h6",
        best_move_san="Nxh6",
        score_cp=206, mate_in=None,
        wdl_win=990, wdl_draw=10, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="black",
        played_move="Nxh6",
    ),

    # pos_15 — 12... Nhxf5
    "pos_15": EngineResult(
        fen="r2q1rk1/ppp2ppp/3p3n/4pB2/P1PnP3/3P4/1P1N1PP1/R2QK1NR b - - 0 0",
        best_move_uci="h6f5",
        best_move_san="Nxf5",
        score_cp=-249, mate_in=None,
        wdl_win=0, wdl_draw=0, wdl_loss=1000,
        depth=15, shashin_type="Petrosian",
        side_to_move="black",
        played_move="Nhxf5",
    ),

    # pos_16 — 17... dxe4
    "pos_16": EngineResult(
        fen="r2q1rk1/ppp2pp1/5P1p/3pp2Q/P1P1N3/3P4/1P3PP1/n2K2NR b - - 0 0",
        best_move_uci="d5e4",
        best_move_san="dxe4",
        score_cp=621, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="black",
        played_move="dxe4",
    ),

    # pos_17 — 6. Qe2
    "pos_17": EngineResult(
        fen="rnbqkb1r/ppp1n2p/4p1p1/3p1p1Q/3P4/4P3/PPPN1PPP/RNB1KB1R w - - 0 0",
        best_move_uci="h5d1",
        best_move_san="Qd1",
        score_cp=-5, mate_in=None,
        wdl_win=20, wdl_draw=960, wdl_loss=30,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="Qe2",
    ),

    # pos_18 — 41... Ka8
    "pos_18": EngineResult(
        fen="1k6/p7/2N5/2R5/6bP/2KB4/r7/8 b - - 0 0",
        best_move_uci="b8b7",
        best_move_san="Kb7",
        score_cp=-381, mate_in=None,
        wdl_win=0, wdl_draw=0, wdl_loss=1000,
        depth=15, shashin_type="Petrosian",
        side_to_move="black",
        played_move="Ka8",
    ),

    # pos_19 — 44. Rxa5+
    "pos_19": EngineResult(
        fen="k7/8/2N5/p4R2/7P/2K5/r7/8 w - - 0 0",
        best_move_uci="f5f7",
        best_move_san="Rf7",
        score_cp=None, mate_in=5,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Rxa5+",
    ),

    # pos_20 — 65. Kf3
    "pos_20": EngineResult(
        fen="8/8/8/8/5K2/3Q4/8/6k1 w - - 0 0",
        best_move_uci="f4g3",
        best_move_san="Kg3",
        score_cp=None, mate_in=2,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Kf3",
    ),

    # pos_21 — 14... Na7
    "pos_21": EngineResult(
        fen="r1b2rk1/3p1ppp/1pnb4/pP4q1/8/2P1PBP1/3P3P/RNBQK2R b - - 0 0",
        best_move_uci="g5b5",
        best_move_san="Qxb5",
        score_cp=157, mate_in=None,
        wdl_win=930, wdl_draw=70, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="black",
        played_move="Na7",
    ),

    # pos_22 — 36... Qc2+
    "pos_22": EngineResult(
        fen="2Q5/5ppk/1p3b2/p7/3Pq3/1KP1n1P1/7P/1R2R3 b - - 0 0",
        best_move_uci="e4c2",
        best_move_san="Qc2",
        score_cp=830, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="black",
        played_move="Qc2+",
    ),

    # pos_23 — 42. d5
    "pos_23": EngineResult(
        fen="8/5ppk/1p6/8/1K1P4/4R1P1/2q4P/8 w - - 0 0",
        best_move_uci="e3e5",
        best_move_san="Re5",
        score_cp=-503, mate_in=None,
        wdl_win=0, wdl_draw=0, wdl_loss=1000,
        depth=15, shashin_type="Petrosian",
        side_to_move="white",
        played_move="d5",
    ),

    # pos_24 — 7. Qg5
    "pos_24": EngineResult(
        fen="r1bqk2r/ppp2ppp/2n1pn2/3p4/3P4/5NP1/PPPQPPP1/RN2KB1R w - - 0 0",
        best_move_uci="e2e3",
        best_move_san="e3",
        score_cp=75, mate_in=None,
        wdl_win=220, wdl_draw=770, wdl_loss=0,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="Qg5",
    ),

    # pos_25 — 2. Nf3
    "pos_25": EngineResult(
        fen="rnbqkbnr/pppp1ppp/4p3/8/4P3/8/PPPP1PPP/RNBQKBNR w - - 0 0",
        best_move_uci="d2d4",
        best_move_san="d4",
        score_cp=44, mate_in=None,
        wdl_win=100, wdl_draw=900, wdl_loss=0,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="Nf3",
    ),

    # pos_26 — 16. h3
    "pos_26": EngineResult(
        fen="r5k1/pbpp1ppp/1p6/3P4/2B3n1/2N2N2/PPP2PPP/4R1K1 w - - 0 0",
        best_move_uci="d5d6",
        best_move_san="d6",
        score_cp=504, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="h3",
    ),

    # pos_27 — 11. Ne2
    "pos_27": EngineResult(
        fen="r2qkb1r/1p1n1pp1/p1p1p2p/3pPn2/1P1P4/P1NQ1N2/2P2PPP/R1B2RK1 w - - 0 0",
        best_move_uci="c3a4",
        best_move_san="Na4",
        score_cp=43, mate_in=None,
        wdl_win=70, wdl_draw=930, wdl_loss=0,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="Ne2",
    ),

    # pos_28 — 18... Nc5
    "pos_28": EngineResult(
        fen="b2q1rk1/3pb1pp/n1n1p3/p3Np2/2PpPB2/P2Q1P2/1P4PP/4RRK1 b - - 0 0",
        best_move_uci="f5e4",
        best_move_san="fxe4",
        score_cp=453, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="black",
        played_move="Nc5",
    ),

    # pos_29 — 19. Qd1
    "pos_29": EngineResult(
        fen="b2q1rk1/3pb1pp/2n1p3/p1n1Np2/2PpPB2/P2Q1P2/1P4PP/4RRK1 w - - 0 0",
        best_move_uci="d3d1",
        best_move_san="Qd1",
        score_cp=-403, mate_in=None,
        wdl_win=0, wdl_draw=0, wdl_loss=1000,
        depth=15, shashin_type="Petrosian",
        side_to_move="white",
        played_move="Qd1",
    ),

    # pos_30 — 8... Nf5
    "pos_30": EngineResult(
        fen="rnb1kb1r/pppqnp1p/4p1p1/3pP3/3P1NQ1/2N1B3/PPP2PPP/R3KB1R b - - 0 0",
        best_move_uci="a7a6",
        best_move_san="a6",
        score_cp=-28, mate_in=None,
        wdl_win=10, wdl_draw=930, wdl_loss=60,
        depth=15, shashin_type="Capablanca",
        side_to_move="black",
        played_move="Nf5",
    ),

    # pos_31 — 6. Nxf7
    "pos_31": EngineResult(
        fen="r1bqk2r/pp1pbppp/2n2n2/2p1p1N1/2B1P3/5Q2/PPPP1PPP/RNB1K2R w - - 0 0",
        best_move_uci="g5f7",
        best_move_san="Nxf7",
        score_cp=195, mate_in=None,
        wdl_win=970, wdl_draw=30, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Nxf7",
    ),

    # pos_32 — 7. Nxh8
    "pos_32": EngineResult(
        fen="r1b1k2r/pp1pbNpp/2n2n2/q1p1p3/2B1P3/5Q2/PPPP1PPP/RNB1K2R w - - 0 0",
        best_move_uci="f7h8",
        best_move_san="Nxh8",
        score_cp=267, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Nxh8",
    ),

    # pos_33 — 12. Qh5+
    "pos_33": EngineResult(
        fen="r3k2N/pp2b1pp/8/q1pPpb2/8/8/PPnP1PPP/RNBQ1RK1 w - - 0 0",
        best_move_uci="d1h5",
        best_move_san="Qh5",
        score_cp=435, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Qh5+",
    ),

    # pos_34 — 12... g6
    "pos_34": EngineResult(
        fen="r3k2N/pp2b1pp/8/q1pPpb1Q/8/8/PPnP1PPP/RNB2RK1 b - - 0 0",
        best_move_uci="g7g6",
        best_move_san="g6",
        score_cp=-431, mate_in=None,
        wdl_win=0, wdl_draw=0, wdl_loss=1000,
        depth=15, shashin_type="Petrosian",
        side_to_move="black",
        played_move="g6",
    ),

    # pos_35 — 11. a4
    "pos_35": EngineResult(
        fen="r2qkb1r/p2nnpp1/4p2p/1p1pPb2/2pP4/1PP1BN2/P2NBPPP/R2Q1RK1 w - - 0 0",
        best_move_uci="a2a4",
        best_move_san="a4",
        score_cp=103, mate_in=None,
        wdl_win=500, wdl_draw=500, wdl_loss=0,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="a4",
    ),

    # pos_36 — 8... c6
    "pos_36": EngineResult(
        fen="rnb1qrk1/ppp1p1bp/3p1np1/5p2/2PP4/2N2NP1/PPQ1PPBP/R1B2RK1 b - - 0 0",
        best_move_uci="e7e5",
        best_move_san="e5",
        score_cp=-12, mate_in=None,
        wdl_win=10, wdl_draw=950, wdl_loss=30,
        depth=15, shashin_type="Capablanca",
        side_to_move="black",
        played_move="c6",
    ),

    # pos_37 — 13... Ng4
    "pos_37": EngineResult(
        fen="r1b2rk1/ppn1pqbp/2p2np1/2Pp1p2/3P3N/PPN3P1/1BQ1PPBP/R4RK1 b - - 0 0",
        best_move_uci="f5f4",
        best_move_san="f4",
        score_cp=76, mate_in=None,
        wdl_win=270, wdl_draw=730, wdl_loss=0,
        depth=15, shashin_type="Capablanca",
        side_to_move="black",
        played_move="Ng4",
    ),

    # pos_38 — 10... Nd7
    "pos_38": EngineResult(
        fen="r1b1k2r/ppp2ppp/4pn2/4P3/2B5/4P3/PP1N1PPP/R3K2R b - - 0 0",
        best_move_uci="f6d7",
        best_move_san="Nd7",
        score_cp=-51, mate_in=None,
        wdl_win=0, wdl_draw=960, wdl_loss=40,
        depth=15, shashin_type="Capablanca",
        side_to_move="black",
        played_move="Nd7",
    ),

    # pos_39 — 14. Bb5
    "pos_39": EngineResult(
        fen="r4rk1/pbpn1ppp/1p2p3/4P3/2B2P2/4P3/PP1N2PP/2R2RK1 w - - 0 0",
        best_move_uci="c4e2",
        best_move_san="Be2",
        score_cp=60, mate_in=None,
        wdl_win=60, wdl_draw=940, wdl_loss=0,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="Bb5",
    ),

    # pos_40 — 15... f6
    "pos_40": EngineResult(
        fen="r4rk1/pbp2ppp/1p2p3/1Bn1P3/5PP1/4P3/PP1N3P/2R2RK1 b - - 0 0",
        best_move_uci="a8d8",
        best_move_san="Rd8",
        score_cp=-5, mate_in=None,
        wdl_win=0, wdl_draw=1000, wdl_loss=0,
        depth=15, shashin_type="Capablanca",
        side_to_move="black",
        played_move="f6",
    ),

    # pos_41 — 17. Bc6
    "pos_41": EngineResult(
        fen="r4rk1/p1p3pp/bp2pp2/1Bn1P3/1P3PP1/4P3/P2N3P/2R2RK1 w - - 0 0",
        best_move_uci="b5a6",
        best_move_san="Bxa6",
        score_cp=71, mate_in=None,
        wdl_win=120, wdl_draw=880, wdl_loss=0,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="Bc6",
    ),

    # pos_42 — 24. Ne4
    "pos_42": EngineResult(
        fen="r5k1/2R4p/pp3p2/1b3P2/1P6/4P3/P2N3P/6K1 w - - 0 0",
        best_move_uci="d2e4",
        best_move_san="Ne4",
        score_cp=291, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Ne4",
    ),

    # pos_43 — 28. Rxa6
    "pos_43": EngineResult(
        fen="1r4k1/7p/p1RN1p2/1p3P2/PP6/3bP3/7P/6K1 w - - 0 0",
        best_move_uci="a4a5",
        best_move_san="a5",
        score_cp=421, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Rxa6",
    ),

    # pos_44 — 35. Kf3
    "pos_44": EngineResult(
        fen="6k1/7p/3N1p2/P7/8/3bP3/5K1P/8 w - - 0 0",
        best_move_uci="d6e8",
        best_move_san="Ne8",
        score_cp=359, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Kf3",
    ),

    # pos_45 — 35... Kf8
    "pos_45": EngineResult(
        fen="6k1/7p/3N1p2/P7/8/3bPK2/7P/8 b - - 0 0",
        best_move_uci="g8g7",
        best_move_san="Kg7",
        score_cp=-403, mate_in=None,
        wdl_win=0, wdl_draw=0, wdl_loss=1000,
        depth=15, shashin_type="Petrosian",
        side_to_move="black",
        played_move="Kf8",
    ),

    # pos_46 — 48... Ba8
    "pos_46": EngineResult(
        fen="2N5/P7/2b2p2/3k3P/8/4K3/8/8 b - - 0 0",
        best_move_uci="d5e5",
        best_move_san="Ke5",
        score_cp=-628, mate_in=None,
        wdl_win=0, wdl_draw=0, wdl_loss=1000,
        depth=15, shashin_type="Petrosian",
        side_to_move="black",
        played_move="Ba8",
    ),

    # pos_47 — 31... Nb6
    "pos_47": EngineResult(
        fen="1kn3r1/7q/2p1p3/1p1pPp2/pP1P3P/P1P2N1Q/8/2K4R b - - 0 0",
        best_move_uci="h7h5",
        best_move_san="Qh5",
        score_cp=171, mate_in=None,
        wdl_win=990, wdl_draw=10, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="black",
        played_move="Nb6",
    ),

    # pos_48 — 19. Bg5
    "pos_48": EngineResult(
        fen="6rr/pbpknRpN/1p2p3/3pP3/2nP4/P1PB2P1/2P4P/R1B3K1 w - - 0 0",
        best_move_uci="c1g5",
        best_move_san="Bg5",
        score_cp=477, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Bg5",
    ),

    # pos_49 — 2. e3
    "pos_49": EngineResult(
        fen="rnbqkb1r/pppppppp/5n2/8/3P4/8/PPP1PPPP/RNBQKBNR w - - 0 0",
        best_move_uci="c2c4",
        best_move_san="c4",
        score_cp=36, mate_in=None,
        wdl_win=80, wdl_draw=920, wdl_loss=10,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="e3",
    ),

    # pos_50 — 2... c5
    "pos_50": EngineResult(
        fen="rnbqkb1r/pppppppp/5n2/8/3P4/4P3/PPP2PPP/RNBQKBNR b - - 0 0",
        best_move_uci="e7e6",
        best_move_san="e6",
        score_cp=-18, mate_in=None,
        wdl_win=10, wdl_draw=950, wdl_loss=40,
        depth=15, shashin_type="Capablanca",
        side_to_move="black",
        played_move="c5",
    ),

    # pos_51 — 13. Ndf3
    "pos_51": EngineResult(
        fen="r2qr1k1/pb1n1ppp/2nbp3/1p1pN3/2pPPP2/2P5/PPBN2PP/R1B1QRK1 w - - 0 0",
        best_move_uci="e5d7",
        best_move_san="Nxd7",
        score_cp=224, mate_in=None,
        wdl_win=990, wdl_draw=10, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="white",
        played_move="Ndf3",
    ),

    # pos_52 — 17... Nf8
    "pos_52": EngineResult(
        fen="r2qr1k1/p2nb1pp/2b1p3/1p1pP3/2pP4/2P2NQ1/PPB3PP/R1B2RK1 b - - 0 0",
        best_move_uci="d8c7",
        best_move_san="Qc7",
        score_cp=-500, mate_in=None,
        wdl_win=0, wdl_draw=0, wdl_loss=1000,
        depth=15, shashin_type="Petrosian",
        side_to_move="black",
        played_move="Nf8",
    ),

    # pos_53 — 12. f5
    "pos_53": EngineResult(
        fen="rn2q2N/pp4pp/2kbp3/2p5/4pPB1/8/PPPP2PP/RNB1K2R w - - 0 0",
        best_move_uci="b1c3",
        best_move_san="Nc3",
        score_cp=-78, mate_in=None,
        wdl_win=0, wdl_draw=810, wdl_loss=190,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="f5",
    ),

    # pos_54 — 14. Rf1
    "pos_54": EngineResult(
        fen="r3q2N/pp1n2pp/2kb4/2p2B2/4p3/8/PPPP2PP/RNB1K2R w - - 0 0",
        best_move_uci="h8f7",
        best_move_san="Nf7",
        score_cp=-250, mate_in=None,
        wdl_win=0, wdl_draw=0, wdl_loss=1000,
        depth=15, shashin_type="Petrosian",
        side_to_move="white",
        played_move="Rf1",
    ),

    # pos_55 — 14... Nf6
    "pos_55": EngineResult(
        fen="r3q2N/pp1n2pp/2kb4/2p2B2/4p3/8/PPPP2PP/RNB1KR2 b - - 0 0",
        best_move_uci="g7g6",
        best_move_san="g6",
        score_cp=232, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="black",
        played_move="Nf6",
    ),

    # pos_56 — 21... Be5
    "pos_56": EngineResult(
        fen="4r3/ppb1q1p1/2k2n2/2p3B1/8/3B4/PPP1N1P1/R3KR2 b - - 0 0",
        best_move_uci="c5c4",
        best_move_san="c4",
        score_cp=471, mate_in=None,
        wdl_win=1000, wdl_draw=0, wdl_loss=0,
        depth=15, shashin_type="Tal",
        side_to_move="black",
        played_move="Be5",
    ),

    # pos_57 — 40. Rf1
    "pos_57": EngineResult(
        fen="8/pB3pkp/P7/8/6nP/4P1P1/3r1PK1/2R5 w - - 0 0",
        best_move_uci="g2g1",
        best_move_san="Kg1",
        score_cp=111, mate_in=None,
        wdl_win=680, wdl_draw=320, wdl_loss=0,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="Rf1",
    ),

    # pos_58 — 26. b4
    "pos_58": EngineResult(
        fen="6rr/pp1kb3/4p3/2npP3/3B2Pp/P4N2/1PP2K2/R5R1 w - - 0 0",
        best_move_uci="f2e3",
        best_move_san="Ke3",
        score_cp=-125, mate_in=None,
        wdl_win=0, wdl_draw=190, wdl_loss=810,
        depth=15, shashin_type="Capablanca",
        side_to_move="white",
        played_move="b4",
    ),

    # pos_59 — 17. Re1
    "pos_59": EngineResult(
        fen="r1b2rk1/1p2nppp/2n1p3/1B1p4/Pb1B4/4PN2/2q2PPP/1N1R2K1 w - - 0 0",
        best_move_uci="b1c3",
        best_move_san="Nc3",
        score_cp=-920, mate_in=None,
        wdl_win=0, wdl_draw=0, wdl_loss=1000,
        depth=15, shashin_type="Petrosian",
        side_to_move="white",
        played_move="Re1",
    ),

}


def get_mock_result(position_key: str) -> EngineResult:
    return MOCK_POSITIONS[position_key]
